/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as LibraryImport } from './routes/library'
import { Route as DownloadsImport } from './routes/downloads'
import { Route as InfoIdImport } from './routes/info/$id'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const LibraryRoute = LibraryImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRoute,
} as any)

const DownloadsRoute = DownloadsImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const InfoIdRoute = InfoIdImport.update({
  id: '/info/$id',
  path: '/info/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsImport
      parentRoute: typeof rootRoute
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/info/$id': {
      id: '/info/$id'
      path: '/info/$id'
      fullPath: '/info/$id'
      preLoaderRoute: typeof InfoIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/downloads': typeof DownloadsRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/info/$id': typeof InfoIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/downloads': typeof DownloadsRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/info/$id': typeof InfoIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/downloads': typeof DownloadsRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/info/$id': typeof InfoIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/downloads' | '/library' | '/settings' | '/info/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/downloads' | '/library' | '/settings' | '/info/$id'
  id: '__root__' | '/' | '/downloads' | '/library' | '/settings' | '/info/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DownloadsRoute: typeof DownloadsRoute
  LibraryRoute: typeof LibraryRoute
  SettingsRoute: typeof SettingsRoute
  InfoIdRoute: typeof InfoIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DownloadsRoute: DownloadsRoute,
  LibraryRoute: LibraryRoute,
  SettingsRoute: SettingsRoute,
  InfoIdRoute: InfoIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/downloads",
        "/library",
        "/settings",
        "/info/$id"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/downloads": {
      "filePath": "downloads.tsx"
    },
    "/library": {
      "filePath": "library.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/info/$id": {
      "filePath": "info/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
