name: build

on:
  push:
    branches:
      - release

jobs:
  build_publish:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    env:
      VITE_TWITCH_CLIENT_ID: ${{ secrets.VITE_TWITCH_CLIENT_ID }}
      VITE_TWITCH_CLIENT_SECRET: ${{ secrets.VITE_TWITCH_CLIENT_SECRET }}
      VITE_ITAD_API_KEY: ${{ secrets.VITE_ITAD_API_KEY }}
      VITE_STEAMGRIDDB_API_KEY: ${{ secrets.VITE_STEAMGRIDDB_API_KEY }}
      VITE_RD_CLIENT_ID: ${{ secrets.VITE_RD_CLIENT_ID }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun
            ~/.cache/bun
            ~/.bun/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: ${{ runner.os }}-bun-

      - name: install bun
        uses: oven-sh/setup-bun@v2

      - name: install dependencies
        run: bun install

      - name: build linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-tools fakeroot dpkg snapd flatpak flatpak-builder rpm
          sudo ln -s /snap/bin/snapcraft /usr/local/bin/snapcraft
          sudo snap install snapcraft --classic
          bun run prebuild && bun run build:linux

      - name: build windows
        if: matrix.os == 'windows-latest'
        run: bun run prebuild && bun run build:win

      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: |
            release/**
            dist/**
            dist-electron/**

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            release/*.exe
            release/*.AppImage
            release/*.deb
            release/*.rpm
            release/*.snap
            release/*.pacman
            release/*.yml
